### ISSUE TITLE
Changes saved toward a Postgis table?

### ISSUE THREAD

**Issue by image80** [gacarrillor/AppendFeaturesToLayer#10]
Hello. It was simply to know if it was possible to save modifications toward a postgis table? (Postgresql Postgis serveur).
Thanks.

**Comment by gacarrillor** [comment]
> Hello. It was simply to know if it was possible to save modifications toward a postgis table? (Postgresql Postgis serveur).

If you have been granted write access, yes.

If you find any trouble don't hesitate to let us know.

Regards

**Comment by brusspi** [comment]
Hi,

I am testing your plugin to integrate it into our workflow.  Appending works fine.  But when choosing update, then it gives an error, saying that the target layer does not support updating.  But that's not true.  See images 
![2023-07-13 11_19_08-Append Features to Layer](https://github.com/gacarrillor/AppendFeaturesToLayer/assets/22054404/9746db44-834b-4d17-8d8d-e06fc4777c3b)
![2023-07-13 11_20_02-DB Manager](https://github.com/gacarrillor/AppendFeaturesToLayer/assets/22054404/d401f209-e518-428c-98df-cbdec6938310)

**Comment by gacarrillor** [comment]
Hi, could you let me know what is the result of running the following Python code in the QGIS Python console?

(Before running it, make sure you have your target PostgreSQL layer selected in the "Layers panel")

```
caps = iface.activeLayer().dataProvider().capabilities()
bool(caps & QgsVectorDataProvider.ChangeAttributeValues)
bool(caps & QgsVectorDataProvider.ChangeGeometries)
```
You should get 2 boolean values.

**Comment by brusspi** [comment]
this is the result

`caps = iface.activeLayer().dataProvider().capabilities()
bool(caps & QgsVectorDataProvider.ChangeAttributeValues)
True
bool(caps & QgsVectorDataProvider.ChangeGeometries)
False`

**Comment by gacarrillor** [comment]
Great, that's what I was expecting.

Could you test the development version I'm attaching as ZIP and let me know if it fixes the issue you're reporting?

[AppendFeaturesToLayer.zip](https://github.com/gacarrillor/AppendFeaturesToLayer/files/12074980/AppendFeaturesToLayer.zip)

**Comment by brusspi** [comment]
Yes, now it works as expected.  Great!

**Comment by gacarrillor** [comment]
Nice, we'll release soon a new public version with this fix included.

Consider starring this project in GitHub and even [rating it in QGIS](https://plugins.qgis.org/plugins/AppendFeaturesToLayer/) since it is useful four your work.

Closing now as fixed.
